<?php
// Connexion à la base de données
include("includes/identifiants.php");


// Insertion du message à l'aide d'une requête préparée

$Combat='';

$i=1;
$idarme = "idarme".$i;
while ( $i<= 6) {
	if ($_POST[$idarme] != 0) {
		$attarme = 'attarme'.$i;
		$damarme = 'damarme'.$i;
		$pararme = 'pararme'.$i;
		$Combat .= $_POST[$idarme].';'.$_POST[$attarme].';'.$_POST[$damarme].';'.$_POST[$pararme].';';
	}
	$i++;
	$idarme = "idarme".$i;
}

$per = $bdd->prepare("INSERT INTO personnage (/*id_joueur,*/nom,
	sexe,
	age,
	yeux,
	cheveux,
	id_nationalite,
	id_classe_social1,
	id_classe_social2,
	id_classe_social3,
	id_culte,
	Point_Elan,
	Argent,
	Combat,
	forc,
	constitution,
	taille,
	intelligence,
	pouvoir,
	dexterite,
	charisme,
	sante_mental,
	pv_max,
	pv,
	SFT,
	connaissance_bonus,
	evaluer_tresor,
	premier_soin,
	cartographie,
	memoriser,
	connaissance_plantes,
	connaissance_poisons,
	artisanat,
	LLC,
	PLC,
	LBM,
	PBM,
	LHM,
	PHM,
	LP,
	PP,
	LM,
	PM,
	LO,
	PO,
	perception_bonus,
	equilibre,
	ecouter,
	sentir,
	chercher,
	voir,
	gouter,
	pister,
	communication_bonus,
	credit,
	eloquence,
	persuader,
	chanter,
	manipulation_bonus,
	jongler,
	crocheter,
	passe_passe,
	faire_piege,
	faire_noeud,
	agilite_bonus,
	grimper,
	eviter,
	sauter,
	equitation,
	nager,
	culbuter,
	discretion_bonus,
	embuscade,
	dissimuler,
	se_cacher,
	mouvement_silencieux,
	couper_bourse,
	Possesion,
	Invocation) VALUES(/*id_joueur,*/:nom,
	:sexe,
	:age,
	:yeux,
	:cheveux,
	:id_nationalite,
	:id_classe_social1,
	:id_classe_social2,
	:id_classe_social3,
	:id_culte,
	:Point_Elan,
	:Argent,
	:Combat,
	:forc,
	:constitution,
	:taille,
	:intelligence,
	:pouvoir,
	:dexterite,
	:charisme,
	:sante_mental,
	:pv_max,
	:pv,
	:SFT,
	:connaissance_bonus,
	:evaluer_tresor,
	:premier_soin,
	:cartographie,
	:memoriser,
	:connaissance_plantes,
	:connaissance_poisons,
	:artisanat,
	:LLC,
	:PLC,
	:LBM,
	:PBM,
	:LHM,
	:PHM,
	:LP,
	:PP,
	:LM,
	:PM,
	:LO,
	:PO,
	:perception_bonus,
	:equilibre,
	:ecouter,
	:sentir,
	:chercher,
	:voir,
	:gouter,
	:pister,
	:communication_bonus,
	:credit,
	:eloquence,
	:persuader,
	:chanter,
	:manipulation_bonus,
	:jongler,
	:crocheter,
	:passe_passe,
	:faire_piege,
	:faire_noeud,
	:agilite_bonus,
	:grimper,
	:eviter,
	:sauter,
	:equitation,
	:nager,
	:culbuter,
	:discretion_bonus,
	:embuscade,
	:dissimuler,
	:se_cacher,
	:mouvement_silencieux,
	:couper_bourse,
	:Possesion,
	:Invocation)");


$per->execute(array('nom' => $_POST['nom'],
					'sexe' => $_POST['sexe'],
					'age' => $_POST['age'],
					'yeux' => $_POST['yeux_couleur'],
					'cheveux' => $_POST['cheveux'],
					'id_nationalite' => $_POST['id_nationalite'],
					'id_classe_social1' => $_POST['SC1'],
					'id_classe_social2' => $_POST['SC2'],
					'id_classe_social3' => $_POST['SC3'],
					'id_culte' => $_POST['cult'],
					'Point_Elan' => $_POST['Point_Elan'],
					'Argent' => $_POST['Argent'],
					'Combat' => $Combat,
					'forc' => $_POST['forc'],
					'constitution' => $_POST['constitution'],
					'taille' => $_POST['taille'],
					'intelligence' => $_POST['intelligence'],
					'pouvoir' => $_POST['pouvoir'],
					'dexterite' => $_POST['dexterite'],
					'charisme' => $_POST['charisme'],
					'sante_mental' => $_POST['sante_mental'],
					'pv_max' => $_POST['pv_max'],
					'pv' => $_POST['pv'],
					'SFT' => $_POST['SFT'],
					'connaissance_bonus' => $_POST['connaissance_bonus'],
					'evaluer_tresor' => $_POST['evaluer_tresor'],
					'premier_soin' => $_POST['premier_soin'],
					'cartographie' => $_POST['cartographie'],
					'memoriser' => $_POST['memoriser'],
					'connaissance_plantes' => $_POST['connaissance_plantes'],
					'connaissance_poisons' => $_POST['connaissance_poisons'],
					'artisanat' => $_POST['artisanat'],
					'LLC' => $_POST['LLC'],
					'PLC' => $_POST['PLC'],
					'LBM' => $_POST['LBM'],
					'PBM' => $_POST['PBM'],
					'LHM' => $_POST['LHM'],
					'PHM' => $_POST['PHM'],
					'LP' => $_POST['LP'],
					'PP' => $_POST['PP'],
					'LM' => $_POST['LM'],
					'PM' => $_POST['PM'],
					'LO' => $_POST['LO'],
					'PO' => $_POST['PO'],
					'perception_bonus' => $_POST['perception_bonus'],
					'equilibre' => $_POST['equilibre'],
					'ecouter' => $_POST['ecouter'],
					'sentir' => $_POST['sentir'],
					'chercher' => $_POST['chercher'],
					'voir' => $_POST['voir'],
					'gouter' => $_POST['gouter'],
					'pister' => $_POST['pister'],
					'communication_bonus' => $_POST['communication_bonus'],
					'credit' => $_POST['credit'],
					'eloquence' => $_POST['eloquence'],
					'persuader' => $_POST['persuader'],
					'chanter' => $_POST['chanter'],
					'manipulation_bonus' => $_POST['manipulation_bonus'],
					'jongler' => $_POST['jongler'],
					'crocheter' => $_POST['crocheter'],
					'passe_passe' => $_POST['passe_passe'],
					'faire_piege' => $_POST['faire_piege'],
					'faire_noeud' => $_POST['faire_noeud'],
					'agilite_bonus' => $_POST['agilite_bonus'],
					'grimper' => $_POST['grimper'],
					'eviter' => $_POST['eviter'],
					'sauter' => $_POST['sauter'],
					'equitation' => $_POST['equitation'],
					'nager' => $_POST['nager'],
					'culbuter' => $_POST['culbuter'],
					'discretion_bonus' => $_POST['discretion_bonus'],
					'embuscade' => $_POST['embuscade'],
					'dissimuler' => $_POST['dissimuler'],
					'se_cacher' => $_POST['se_cacher'],
					'mouvement_silencieux' => $_POST['mouvement_silencieux'],
					'couper_bourse' => $_POST['couper_bourse'],
					'Possesion' => $_POST['Possession'],
					'Invocation' => $_POST['Invocation']
 ))
					

?>